### ISSUE TITLE
Define the structure for the new index.yaml and collection.yaml

### ISSUE THREAD

**Issue by groeges** [kabanero-io/kabanero-collection#40]
With the collections repo being forked from the appsody/stacks repo we need to utilise the build process and file structure that that repo is using. 

We need to add the collection information (pipelines, images, dashboards, operators, etc) into the index.yaml file in a way that will not cause the appsody application (cli) from being able to work.

The appsody build process generates the index.yaml for each stack based on the stack.yaml and the files (templates) that are in the git repo. For the collection we will use a single collection.yaml within the stack directory and the git repo to generate all the artifacts etc for the collection.

**Comment by groeges** [comment]
An example of the collection.yaml is:
```
maintainers:
  - name: Ian Partridge
    email: i.partridge@uk.ibm.com
    github-id: ianpartridge
default-template: new
default-image: nodejs-ubi
default-pipeline: default
default-dashboard: default
images:
  - id: nodejs
    image: appsody/nodejs:0.2
  - id: nodejs_ubi
    image: kabanero/nodejs:0.1
```
Any elements in the collection.yaml will override those defined in the stack.yaml.
The  details for the pipelines, dashboards, operators will be generated from the files in the git repo.

**Comment by groeges** [comment]
A example of the generated index.yaml is:
```
apiVersion: v2
stacks:
  - id: nodejs-express
    name: Node.js Express
    version: 0.2.1
    description: Express web framework for Node.js
    license: Apache-2.0
    maintainers:
      - name: Chris Bailey
        email: cnbailey@gmail.com
        github-id: seabaylea
      - name: Neeraj Laad
        email: neeraj.laad@gmail.com
        github-id: neeraj-laad
    default-template: simple
    default-dashboard: default
    default-image: nodejs-ubi
    default-pipeline: default
    templates:
      - id: simple
        url: https://github.com//releases/download/nodejs-express-v0.2.1/incubator.nodejs-express.simple.tar.gz
      - id: skaffold
        url: https://github.com//releases/download/nodejs-express-v0.2.1/incubator.nodejs-express.skaffold.tar.gz
    images:
    - id: nodejs_ubi
      image: kabanero/nodejs:0.1
    pipelines:
      - id: default
        url: https://github.com//releases/latest/download/incubator.nodejs-express.pipeline.default.tar.gz
    dashboards:
      - id: default
        url: https://github.com//releases/latest/download/incubator.nodejs-express.dashboard.default.tar.gz
  - id: nodejs
    default-template: new
    default-dashboard: default
    default-image: nodejs-ubi
    default-pipeline: default
    images:
    - id: nodejs
      image: appsody/nodejs:0.2
    - id: nodejs_ubi
      image: kabanero/nodejs:0.1
    maintainers:
    - email: i.partridge@uk.ibm.com
      github-id: ianpartridge
      name: Ian Partridge
    templates:
      - id: simple
        url: https://github.com//releases/download/nodejs-v0.2.1/incubator.nodejs.simple.tar.gz
      - id: new
        url: https://github.com//releases/download/nodejs-v0.2.1/incubator.nodejs.new.tar.gz
    pipelines:
      - id: default
        url: https://github.com//releases/latest/download/incubator.nodejs.pipeline.default.tar.gz
      - id: openshift
        url: https://github.com//releases/latest/download/incubator.nodejs.pipeline.openshift.tar.gz
    dashboards:
      - id: default
        url: https://github.com//releases/latest/download/incubator.nodejs.dashboard.default.tar.gz
```
