### ISSUE TITLE
Add artifact to deploy Appsody Application Operator

### ISSUE THREAD

**Issue by arthurdm** [kabanero-io/kabanero-collection#57]
Each Collection will need an `app_cr.yaml` file that represents the minimal set of configuration needed to deploy the application image.

```yaml
apiVersion: appsody.dev/v1alpha1
kind: AppsodyApplication
metadata:
  name: REPLACE-NAME
spec:
  applicationImage: REPLACE-IMAGE
  stack: java-microprofile
```

The field `REPLACE-NAME` should be modified to match the service's name (must be unique), and `REPLACE-IMAGE` should be modified to represent the full image path, such as `registry/imageName:imageTag`.
